# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TWB-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TWB-ios
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    pod 'RxDataSources', '~> 3.0' # for handle tableView collectionView
    pod 'RxGesture', '2.0.1'

    # pod 'SwiftyJSON', '~> 4.0' # json
    # pod 'Alamofire', '~> 4.0' #https request
    pod 'RxAlamofire'
    # pod 'Kingfisher', '~> 3.0' # =>   圖片網路

  target 'TWB-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TWB-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
